// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: execution_logs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExecutionLog = `-- name: CreateExecutionLog :one
INSERT INTO execution_logs (workflow_id, status, trigger_data)
VALUES ($1, $2, $3)
RETURNING id, workflow_id, status, trigger_data, node_logs, started_at, finished_at
`

type CreateExecutionLogParams struct {
	WorkflowID  pgtype.UUID `json:"workflow_id"`
	Status      string      `json:"status"`
	TriggerData []byte      `json:"trigger_data"`
}

func (q *Queries) CreateExecutionLog(ctx context.Context, arg CreateExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, createExecutionLog, arg.WorkflowID, arg.Status, arg.TriggerData)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.TriggerData,
		&i.NodeLogs,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listExecutionLogs = `-- name: ListExecutionLogs :many
SELECT id, workflow_id, status, trigger_data, node_logs, started_at, finished_at FROM execution_logs
WHERE workflow_id = $1
ORDER BY started_at DESC
LIMIT $2 OFFSET $3
`

type ListExecutionLogsParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListExecutionLogs(ctx context.Context, arg ListExecutionLogsParams) ([]ExecutionLog, error) {
	rows, err := q.db.Query(ctx, listExecutionLogs, arg.WorkflowID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExecutionLog
	for rows.Next() {
		var i ExecutionLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.Status,
			&i.TriggerData,
			&i.NodeLogs,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionLog = `-- name: UpdateExecutionLog :one
UPDATE execution_logs
SET status = $2, node_logs = $3, finished_at = $4
WHERE id = $1
RETURNING id, workflow_id, status, trigger_data, node_logs, started_at, finished_at
`

type UpdateExecutionLogParams struct {
	ID         pgtype.UUID        `json:"id"`
	Status     string             `json:"status"`
	NodeLogs   []byte             `json:"node_logs"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) UpdateExecutionLog(ctx context.Context, arg UpdateExecutionLogParams) (ExecutionLog, error) {
	row := q.db.QueryRow(ctx, updateExecutionLog,
		arg.ID,
		arg.Status,
		arg.NodeLogs,
		arg.FinishedAt,
	)
	var i ExecutionLog
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.Status,
		&i.TriggerData,
		&i.NodeLogs,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}
