// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: graph_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGraphState = `-- name: GetGraphState :one
SELECT workflow_id, nodes, edges, updated_at FROM graph_states
WHERE workflow_id = $1 LIMIT 1
`

func (q *Queries) GetGraphState(ctx context.Context, workflowID pgtype.UUID) (GraphState, error) {
	row := q.db.QueryRow(ctx, getGraphState, workflowID)
	var i GraphState
	err := row.Scan(
		&i.WorkflowID,
		&i.Nodes,
		&i.Edges,
		&i.UpdatedAt,
	)
	return i, err
}

const saveGraphState = `-- name: SaveGraphState :one
INSERT INTO graph_states (workflow_id, nodes, edges)
VALUES ($1, $2, $3)
ON CONFLICT (workflow_id) DO UPDATE
SET nodes = EXCLUDED.nodes, edges = EXCLUDED.edges, updated_at = CURRENT_TIMESTAMP
RETURNING workflow_id, nodes, edges, updated_at
`

type SaveGraphStateParams struct {
	WorkflowID pgtype.UUID `json:"workflow_id"`
	Nodes      []byte      `json:"nodes"`
	Edges      []byte      `json:"edges"`
}

func (q *Queries) SaveGraphState(ctx context.Context, arg SaveGraphStateParams) (GraphState, error) {
	row := q.db.QueryRow(ctx, saveGraphState, arg.WorkflowID, arg.Nodes, arg.Edges)
	var i GraphState
	err := row.Scan(
		&i.WorkflowID,
		&i.Nodes,
		&i.Edges,
		&i.UpdatedAt,
	)
	return i, err
}
