// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExecutionLog struct {
	ID          pgtype.UUID        `json:"id"`
	WorkflowID  pgtype.UUID        `json:"workflow_id"`
	Status      string             `json:"status"`
	TriggerData []byte             `json:"trigger_data"`
	NodeLogs    []byte             `json:"node_logs"`
	StartedAt   pgtype.Timestamptz `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
}

type GraphState struct {
	WorkflowID pgtype.UUID        `json:"workflow_id"`
	Nodes      []byte             `json:"nodes"`
	Edges      []byte             `json:"edges"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workflow struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
