// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateExecutionLog(ctx context.Context, arg CreateExecutionLogParams) (ExecutionLog, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error
	GetGraphState(ctx context.Context, workflowID pgtype.UUID) (GraphState, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error)
	ListExecutionLogs(ctx context.Context, arg ListExecutionLogsParams) ([]ExecutionLog, error)
	ListWorkflows(ctx context.Context, userID pgtype.UUID) ([]Workflow, error)
	SaveGraphState(ctx context.Context, arg SaveGraphStateParams) (GraphState, error)
	ToggleWorkflowStatus(ctx context.Context, arg ToggleWorkflowStatusParams) (Workflow, error)
	UpdateExecutionLog(ctx context.Context, arg UpdateExecutionLogParams) (ExecutionLog, error)
	UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error)
}

var _ Querier = (*Queries)(nil)
