// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflows (user_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, description, is_active, created_at, updated_at
`

type CreateWorkflowParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, createWorkflow, arg.UserID, arg.Name, arg.Description)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkflow = `-- name: DeleteWorkflow :exec
DELETE FROM workflows
WHERE id = $1 AND user_id = $2
`

type DeleteWorkflowParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteWorkflow(ctx context.Context, arg DeleteWorkflowParams) error {
	_, err := q.db.Exec(ctx, deleteWorkflow, arg.ID, arg.UserID)
	return err
}

const getWorkflow = `-- name: GetWorkflow :one
SELECT id, user_id, name, description, is_active, created_at, updated_at FROM workflows
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetWorkflowParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetWorkflow(ctx context.Context, arg GetWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, getWorkflow, arg.ID, arg.UserID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkflows = `-- name: ListWorkflows :many
SELECT id, user_id, name, description, is_active, created_at, updated_at FROM workflows
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWorkflows(ctx context.Context, userID pgtype.UUID) ([]Workflow, error) {
	rows, err := q.db.Query(ctx, listWorkflows, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleWorkflowStatus = `-- name: ToggleWorkflowStatus :one
UPDATE workflows
SET is_active = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $3
RETURNING id, user_id, name, description, is_active, created_at, updated_at
`

type ToggleWorkflowStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive bool        `json:"is_active"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ToggleWorkflowStatus(ctx context.Context, arg ToggleWorkflowStatusParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, toggleWorkflowStatus, arg.ID, arg.IsActive, arg.UserID)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflow = `-- name: UpdateWorkflow :one
UPDATE workflows
SET name = $2, description = $3, is_active = $4, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $5
RETURNING id, user_id, name, description, is_active, created_at, updated_at
`

type UpdateWorkflowParams struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) UpdateWorkflow(ctx context.Context, arg UpdateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, updateWorkflow,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.IsActive,
		arg.UserID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
